### ISSUE TITLE
Jekyll stops processing Metro with TypeError

### ISSUE THREAD

**Issue by mwmahlberg** [olakara/JekyllMetro#39]
The environment is set up as follows:

* OS: Mac OSX El Capitan
* Ruby: 2.2.3 via rvm
* Jekyll 3.0.0
* JekyllMetro 0.9x beta 2, dependencies from Gemfile installed via bundler

When calling either `jekyll build` or `jekyll serve`, the processing stops with `default_proc=': wrong default_proc type NilClass (expected Proc) (TypeError)`.

Admittedly, I am totally new to jekyll, but since other themes seem to work (currently investigating which one to use), I thought it might be a problem specific to JekyllMetro.

Here is the output of `-t` for a pristine `_config.yml`:

    Configuration file: /Users/markus/Downloads/JekyllMetro-master/_config.yml
    /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/utils.rb:38:in `default_proc=': wrong default_proc type NilClass (expected Proc) (TypeError)
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/utils.rb:38:in `deep_merge_hashes!'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/utils.rb:15:in `deep_merge_hashes'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/configuration.rb:181:in `block in read_config_files'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/configuration.rb:179:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/configuration.rb:179:in `read_config_files'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll.rb:103:in `configuration'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/command.rb:42:in `configuration_from_options'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:29:in `process'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/jekyll:23:in `load'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/jekyll:23:in `<main>'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mwmahlberg** [comment]
Nevermind, was installing gems to wrong location. Works as a charm now. Thanks a lot.

**Comment by mwmahlberg** [comment]
PebKaC, solved
